In [53]:
import pandas as pd

# Basics

In [ ]:
# tab to auto-filling!
# help() to ask anything

In [8]:
help(pd.read_json)

Help on function read_json in module pandas.io.json._json:

read_json(path_or_buf=None, orient=None, typ='frame', dtype=None, convert_axes=None, convert_dates=True, keep_default_dates: bool = True, numpy: bool = False, precise_float: bool = False, date_unit=None, encoding=None, lines: bool = False, chunksize: Union[int, NoneType] = None, compression: Union[str, Dict[str, Any], NoneType] = 'infer', nrows: Union[int, NoneType] = None, storage_options: Union[Dict[str, Any], NoneType] = None)
    Convert a JSON string to pandas object.

    Parameters
    ----------
    path_or_buf : a valid JSON str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, and file. For file URLs, a host is
        expected. A local file could be:
        ``file://localhost/path/to/table.json``.

        If you want to pass in a path object, pandas accepts any
        ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method,
        such as a file handle (e.g. via builtin ``open`` function)
        or ``StringIO``.
    orient : str
        Indication of expected JSON string format.
        Compatible JSON strings can be produced by ``to_json()`` with a
        corresponding orient value.
        The set of possible orients is:

        - ``'split'`` : dict like
          ``{index -> [index], columns -> [columns], data -> [values]}``
        - ``'records'`` : list like
          ``[{column -> value}, ... , {column -> value}]``
        - ``'index'`` : dict like ``{index -> {column -> value}}``
        - ``'columns'`` : dict like ``{column -> {index -> value}}``
        - ``'values'`` : just the values array

        The allowed and default values depend on the value
        of the `typ` parameter.

        * when ``typ == 'series'``,

          - allowed orients are ``{'split','records','index'}``
          - default is ``'index'``
          - The Series index must be unique for orient ``'index'``.

        * when ``typ == 'frame'``,

          - allowed orients are ``{'split','records','index',
            'columns','values', 'table'}``
          - default is ``'columns'``
          - The DataFrame index must be unique for orients ``'index'`` and
            ``'columns'``.
          - The DataFrame columns must be unique for orients ``'index'``,
            ``'columns'``, and ``'records'``.

    typ : {'frame', 'series'}, default 'frame'
        The type of object to recover.

    dtype : bool or dict, default None
        If True, infer dtypes; if a dict of column to dtype, then use those;
        if False, then don't infer dtypes at all, applies only to the data.

        For all ``orient`` values except ``'table'``, default is True.

        .. versionchanged:: 0.25.0

           Not applicable for ``orient='table'``.

    convert_axes : bool, default None
        Try to convert the axes to the proper dtypes.

        For all ``orient`` values except ``'table'``, default is True.

        .. versionchanged:: 0.25.0

           Not applicable for ``orient='table'``.

    convert_dates : bool or list of str, default True
        If True then default datelike columns may be converted (depending on
        keep_default_dates).
        If False, no dates will be converted.
        If a list of column names, then those columns will be converted and
        default datelike columns may also be converted (depending on
        keep_default_dates).

    keep_default_dates : bool, default True
        If parsing dates (convert_dates is not False), then try to parse the
        default datelike columns.
        A column label is datelike if

        * it ends with ``'_at'``,

        * it ends with ``'_time'``,

        * it begins with ``'timestamp'``,

        * it is ``'modified'``, or

        * it is ``'date'``.

    numpy : bool, default False
        Direct decoding to numpy arrays. Supports numeric data only, but
        non-numeric column and index labels are supported. Note also that the
        JSON ordering MUST be the same for each term if numpy=True.

        .. deprecated:: 1.0.0

    precise_float : bool, default False
        Set to enable usage of higher precision (strtod) function when
        decoding string to double values. Default (False) is to use fast but
        less precise builtin functionality.

    date_unit : str, default None
        The timestamp unit to detect if converting dates. The default behaviour
        is to try and detect the correct precision, but if this is not desired
        then pass one of 's', 'ms', 'us' or 'ns' to force parsing only seconds,
        milliseconds, microseconds or nanoseconds respectively.

    encoding : str, default is 'utf-8'
        The encoding to use to decode py3 bytes.

    lines : bool, default False
        Read the file as a json object per line.

    chunksize : int, optional
        Return JsonReader object for iteration.
        See the `line-delimited json docs
        <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#line-delimited-json>`_
        for more information on ``chunksize``.
        This can only be passed if `lines=True`.
        If this is None, the file will be read into memory all at once.

        .. versionchanged:: 1.2

           ``JsonReader`` is a context manager.

    compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer', then use
        gzip, bz2, zip or xz if path_or_buf is a string ending in
        '.gz', '.bz2', '.zip', or 'xz', respectively, and no decompression
        otherwise. If using 'zip', the ZIP file must contain only one data
        file to be read in. Set to None for no decompression.

    nrows : int, optional
        The number of lines from the line-delimited jsonfile that has to be read.
        This can only be passed if `lines=True`.
        If this is None, all the rows will be returned.

        .. versionadded:: 1.1

    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc., if using a URL that will
        be parsed by ``fsspec``, e.g., starting "s3://", "gcs://". An error
        will be raised if providing this argument with a non-fsspec URL.
        See the fsspec and backend storage implementation docs for the set of
        allowed keys and values.

        .. versionadded:: 1.2.0

    Returns
    -------
    Series or DataFrame
        The type returned depends on the value of `typ`.

    See Also
    --------
    DataFrame.to_json : Convert a DataFrame to a JSON string.
    Series.to_json : Convert a Series to a JSON string.

    Notes
    -----
    Specific to ``orient='table'``, if a :class:`DataFrame` with a literal
    :class:`Index` name of `index` gets written with :func:`to_json`, the
    subsequent read operation will incorrectly set the :class:`Index` name to
    ``None``. This is because `index` is also used by :func:`DataFrame.to_json`
    to denote a missing :class:`Index` name, and the subsequent
    :func:`read_json` operation cannot distinguish between the two. The same
    limitation is encountered with a :class:`MultiIndex` and any names
    beginning with ``'level_'``.

    Examples
    --------
    >>> df = pd.DataFrame([['a', 'b'], ['c', 'd']],
    ...                   index=['row 1', 'row 2'],
    ...                   columns=['col 1', 'col 2'])

    Encoding/decoding a Dataframe using ``'split'`` formatted JSON:

    >>> df.to_json(orient='split')
    '{"columns":["col 1","col 2"],
      "index":["row 1","row 2"],
      "data":[["a","b"],["c","d"]]}'
    >>> pd.read_json(_, orient='split')
          col 1 col 2
    row 1     a     b
    row 2     c     d

    Encoding/decoding a Dataframe using ``'index'`` formatted JSON:

    >>> df.to_json(orient='index')
    '{"row 1":{"col 1":"a","col 2":"b"},"row 2":{"col 1":"c","col 2":"d"}}'
    >>> pd.read_json(_, orient='index')
          col 1 col 2
    row 1     a     b
    row 2     c     d

    Encoding/decoding a Dataframe using ``'records'`` formatted JSON.
    Note that index labels are not preserved with this encoding.

    >>> df.to_json(orient='records')
    '[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'
    >>> pd.read_json(_, orient='records')
      col 1 col 2
    0     a     b
    1     c     d

    Encoding with Table Schema

    >>> df.to_json(orient='table')
    '{"schema": {"fields": [{"name": "index", "type": "string"},
                            {"name": "col 1", "type": "string"},
                            {"name": "col 2", "type": "string"}],
                    "primaryKey": "index",
                    "pandas_version": "0.20.0"},
        "data": [{"index": "row 1", "col 1": "a", "col 2": "b"},
                {"index": "row 2", "col 1": "c", "col 2": "d"}]}'

In [6]:
dfcontent = pd.read_json('all_content.json')

In [9]:
dfcontent.head() # default to 5

,status,sourcer,title_english,title_localized,proficiency,parent_id,tag,content_type,created_date,content_id
0,PUBLISHED,Meho Exclusive,From Alibaba’s payment tool to the largest IPO...,支付宝的成长史,None,None,NaN,Article,2021-03-01T09:03:26.181Z,a5eb9474-cb94-419c-9ab0-b9ede59422ca
1,PUBLISHED,Huxiu / MissXY / The Paper,"30 Years of Development in Pudong, Shanghai - ...",浦东三十年（1）- 邓小平和朱镕基的大动作,None,None,NaN,Article,2021-03-01T09:03:26.159Z,a833f110-bc1d-4acc-b832-5bdefff625ee
2,PUBLISHED,The paper,"A Poetic White Domain in Lujiazui, Shanghai",上海陆家嘴浦东美术馆,None,None,NaN,Article,2021-07-19T06:10:31.959Z,bac40260-3415-4231-b54d-fba6845b4bbf
3,PUBLISHED,Yuanchuan Research,Ultra-High Voltage to lower the cost of solar ...,中国碳中和之路-特高压战略,None,None,NaN,Article,2021-05-16T23:46:23.405Z,e4163bea-a1b6-4d97-b604-692f93c84704
4,PUBLISHED,The Paper,China is changing its storytelling style in en...,叛逆神话人物成为全民英雄,None,None,NaN,Article,2021-03-01T09:03:26.215Z,aded84f9-153c-43b3-a0e9-f5680fbeec4a

In [10]:
dfcontent.tail() # also default to 5

,status,sourcer,title_english,title_localized,proficiency,parent_id,tag,content_type,created_date,content_id
6485,None,None,None,祝贺！谢谢你的盛情招待与地主之谊。,None,fb07bd6f-0860-447d-8009-037a920c9da5,NaN,Chapter,2020-09-07T05:45:42.703Z,bfa96711-c546-49f6-ba0a-fcc24965001c
6486,None,None,None,我也喜欢小说，不过只会买有声书，健身时候听,None,cce5a816-5444-487f-beb2-fc9821e7c8fd,NaN,Chapter,2020-09-07T04:48:21.925Z,9710a989-f580-4bd0-9ead-7557c58198e1
6487,None,None,None,我喜欢读历史书，尤其是关于汉朝和唐朝的历史。你呢？,None,cce5a816-5444-487f-beb2-fc9821e7c8fd,NaN,Chapter,2020-09-07T04:39:01.644Z,5f3807df-5082-4fc1-b499-dd088d0017a3
6488,None,None,None,在商场三楼。前面直走，路口左转。,None,f6d1b3fe-16af-4430-a688-2a39955b28de,NaN,Chapter,2020-09-07T09:50:45.662Z,81a84154-eda6-4e27-9fd7-93fefc5e7617
6489,None,None,None,融合了宫廷服饰和御猫的元素，设计了很多可爱的卡通形象。,None,82937d0e-df52-4bf2-a700-d806a097f95b,NaN,Chapter,2020-09-07T05:14:57.083Z,12520ff5-4c4e-46fa-94ea-8ecabc537385

In [11]:
dfcontent.dtypes  # same as .printSchema

status              object
sourcer             object
title_english       object
title_localized     object
proficiency         object
parent_id           object
tag                float64
content_type        object
created_date        object
content_id          object
dtype: object

In [12]:
dfcontent.shape # get number of rows and column

(6490, 10)

In [13]:
dfcontent.info() # all info you need to know about this df, especially, non-nulls out of all entries for each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6490 entries, 0 to 6489
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   status           86 non-null     object
 1   sourcer          34 non-null     object
 2   title_english    5810 non-null   object
 3   title_localized  5982 non-null   object
 4   proficiency      45 non-null     object
 5   parent_id        1188 non-null   object
 6   tag              0 non-null      float64
 7   content_type     6490 non-null   object
 8   created_date     6490 non-null   object
 9   content_id       6490 non-null   object
dtypes: float64(1), object(9)
memory usage: 507.2+ KB

# Operations on your DF

In [15]:
dfcontent[['title_english', 'tag']].head()  # select multiple columns using double brackets

                                       title_english  tag
0  From Alibaba’s payment tool to the largest IPO...  NaN
1  30 Years of Development in Pudong, Shanghai - ...  NaN
2        A Poetic White Domain in Lujiazui, Shanghai  NaN
3  Ultra-High Voltage to lower the cost of solar ...  NaN
4  China is changing its storytelling style in en...  NaN

In [20]:
dfcontent['title_english'][5:10] # single bracket gives you pandas series, can't select multiple columns
#  but givs you the option to specify [start, end) row index of a DF

5    Social media empowers Chinese fast fashion brands
6     How western elites misjudged the Chinese economy
7    How scalability made solar power 60% cheaper t...
8         Father of Hybrid Rice Yuan Longping’s legacy
9                                                 test
Name: title_english, dtype: object

In [27]:
dfcontent.loc[10:20, ['title_english', 'title_localized']].head(15) # simple ":" gives you all column; removing bracket gives you series

                                        title_english title_localized
10  The flagship baijiu going young and international        茅台发布上头神曲
11  With unsuitable magic from Harry Potter and Fr...          木兰无法突围
12           Tourism in China recovered from COVID-19       史上最挤五一小长假
13  Why Chinese tech companies work 70+ hours a week?     饱受争议的996工作制
14  Chinese culture is attractive again in the mod...        阿木爷爷和李子柒
15  The must-know knowledge in essential Chinese c...    如何在品茶仪式中不犯错误
16  Chinese cities are taking bullet trains to the...       高铁究竟还能跑多快
17  Electric vehicle to make solar power storable ...   中国碳中和之路-电动车战略
18   Its impact on carbon neutrality & climate change    中国比特币挖矿的能耗争议
19   The hottest Chinese idol and his phenomenal song  吴亦凡与现象级的《大碗宽面》
20    The disappearance of rural China from TV & film    乡土中国在荧幕上逐渐消失

In [26]:
dfcontent.loc[10:20, ['title_english']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 10 to 20
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title_english  11 non-null     object
dtypes: object(1)
memory usage: 220.0+ bytes

## Filter

In [32]:
dfcontent['content_type'].value_counts() # check for a given column, what are available values and their tf

Vocabulary        5078
Paragraph          905
Chapter            283
Expression         138
Dialogue            45
Article             34
TrendingPhrase       7
Name: content_type, dtype: int64

In [34]:
articlefilter = dfcontent['content_type']=='Article'

In [35]:
dfcontent[articlefilter].head()

,status,sourcer,title_english,title_localized,proficiency,parent_id,tag,content_type,created_date,content_id
0,PUBLISHED,Meho Exclusive,From Alibaba’s payment tool to the largest IPO...,支付宝的成长史,None,None,NaN,Article,2021-03-01T09:03:26.181Z,a5eb9474-cb94-419c-9ab0-b9ede59422ca
1,PUBLISHED,Huxiu / MissXY / The Paper,"30 Years of Development in Pudong, Shanghai - ...",浦东三十年（1）- 邓小平和朱镕基的大动作,None,None,NaN,Article,2021-03-01T09:03:26.159Z,a833f110-bc1d-4acc-b832-5bdefff625ee
2,PUBLISHED,The paper,"A Poetic White Domain in Lujiazui, Shanghai",上海陆家嘴浦东美术馆,None,None,NaN,Article,2021-07-19T06:10:31.959Z,bac40260-3415-4231-b54d-fba6845b4bbf
3,PUBLISHED,Yuanchuan Research,Ultra-High Voltage to lower the cost of solar ...,中国碳中和之路-特高压战略,None,None,NaN,Article,2021-05-16T23:46:23.405Z,e4163bea-a1b6-4d97-b604-692f93c84704
4,PUBLISHED,The Paper,China is changing its storytelling style in en...,叛逆神话人物成为全民英雄,None,None,NaN,Article,2021-03-01T09:03:26.215Z,aded84f9-153c-43b3-a0e9-f5680fbeec4a

In [40]:
dfcontent.loc[articlefilter, :]  # ":" means all columns

,status,sourcer,title_english,title_localized,proficiency,parent_id,tag,content_type,created_date,content_id
0,PUBLISHED,Meho Exclusive,From Alibaba’s payment tool to the largest IPO...,支付宝的成长史,None,None,NaN,Article,2021-03-01T09:03:26.181Z,a5eb9474-cb94-419c-9ab0-b9ede59422ca
1,PUBLISHED,Huxiu / MissXY / The Paper,"30 Years of Development in Pudong, Shanghai - ...",浦东三十年（1）- 邓小平和朱镕基的大动作,None,None,NaN,Article,2021-03-01T09:03:26.159Z,a833f110-bc1d-4acc-b832-5bdefff625ee
2,PUBLISHED,The paper,"A Poetic White Domain in Lujiazui, Shanghai",上海陆家嘴浦东美术馆,None,None,NaN,Article,2021-07-19T06:10:31.959Z,bac40260-3415-4231-b54d-fba6845b4bbf
3,PUBLISHED,Yuanchuan Research,Ultra-High Voltage to lower the cost of solar ...,中国碳中和之路-特高压战略,None,None,NaN,Article,2021-05-16T23:46:23.405Z,e4163bea-a1b6-4d97-b604-692f93c84704
4,PUBLISHED,The Paper,China is changing its storytelling style in en...,叛逆神话人物成为全民英雄,None,None,NaN,Article,2021-03-01T09:03:26.215Z,aded84f9-153c-43b3-a0e9-f5680fbeec4a
5,PUBLISHED,36Kr,Social media empowers Chinese fast fashion brands,中国崛起快时尚品牌,None,None,NaN,Article,2021-06-27T23:42:16.990Z,63041c65-b4fb-4aa7-a49a-dfa1cb436c58
6,PUBLISHED,Huxiu / MissXY / The Paper,How western elites misjudged the Chinese economy,浦东三十年（2）- 弗里德曼对上海的误判,None,None,NaN,Article,2021-03-01T09:03:26.156Z,79c30ced-a198-456f-b1ca-9399261587a2
7,PUBLISHED,Yuanchuan Research,How scalability made solar power 60% cheaper t...,中国碳中和之路-光伏产业战略,None,None,NaN,Article,2021-05-10T00:55:46.574Z,ec39ec91-b835-4f66-bb63-f0da8ec74aa8
8,PUBLISHED,Sanlian Lifeweek,Father of Hybrid Rice Yuan Longping’s legacy,播下改变中国的种子,None,None,NaN,Article,2021-05-24T00:10:11.675Z,6f9a26fd-3ca0-4732-9496-3de4cc39dbd5
9,ARCHIVED,test,test,test,None,None,NaN,Article,2021-07-18T23:43:13.229Z,7e2e0fac-4839-4650-9e8d-074212cd6142
10,PUBLISHED,The Paper / CHN Fund,The flagship baijiu going young and international,茅台发布上头神曲,None,None,NaN,Article,2021-03-01T09:03:26.129Z,861c8b5c-8c65-46fb-b1cf-2229801bb864
11,PUBLISHED,Gingko Finance,With unsuitable magic from Harry Potter and Fr...,木兰无法突围,None,None,NaN,Article,2021-03-01T09:03:26.193Z,f06ade97-62d9-4219-8d47-fb2e4ff3cc24
12,PUBLISHED,iFeng Weekly,Tourism in China recovered from COVID-19,史上最挤五一小长假,None,None,NaN,Article,2021-05-03T02:36:59.111Z,392ffe1b-3680-41f7-95eb-269d69905e2d
13,PUBLISHED,Lianhe Zaobao,Why Chinese tech companies work 70+ hours a week?,饱受争议的996工作制,None,None,NaN,Article,2021-03-01T09:03:26.193Z,814426c4-6742-42fc-ac96-317ae971ebe2
14,PUBLISHED,Huxiu,Chinese culture is attractive again in the mod...,阿木爷爷和李子柒,None,None,NaN,Article,2021-03-01T09:03:26.157Z,38c9f3a6-a775-4dfc-ace5-5af13c73d347
15,PUBLISHED,Toutiao,The must-know knowledge in essential Chinese c...,如何在品茶仪式中不犯错误,None,None,NaN,Article,2021-03-01T09:03:26.193Z,5fef42eb-961c-40ec-a917-ee1b9ab26427
16,PUBLISHED,China Business Network,Chinese cities are taking bullet trains to the...,高铁究竟还能跑多快,None,None,NaN,Article,2021-03-01T09:03:26.236Z,5276ce75-6328-4e01-b195-b122253f9ad8
17,PUBLISHED,Yuanchuan Research,Electric vehicle to make solar power storable ...,中国碳中和之路-电动车战略,None,None,NaN,Article,2021-05-31T23:34:30.904Z,5107cb77-aaae-43a7-abe1-743bab145507
18,PUBLISHED,The Paper / Colin Wu,Its impact on carbon neutrality & climate change,中国比特币挖矿的能耗争议,None,None,NaN,Article,2021-04-09T18:52:09.929Z,e6851afa-6134-48e9-a262-278b31f510c0
19,PUBLISHED,Toutiao,The hottest Chinese idol and his phenomenal song,吴亦凡与现象级的《大碗宽面》,None,None,NaN,Article,2021-03-01T09:03:26.194Z,d6203af0-a36b-4ead-84e4-5d7cd564abe4
20,PUBLISHED,World of Boss,The disappearance of rural China from TV & film,乡土中国在荧幕上逐渐消失,None,None,NaN,Article,2021-03-01T09:03:26.125Z,f1144955-c3ad-486c-bee5-d4d517455fd9
21,PUBLISHED,Xinmin Evening News,"A day of peace and health, but also happiness",端午安康，端午快乐,None,None,NaN,Article,2021-06-14T02:26:41.839Z,979653e9-962e-44d1-871d-2b31cbb813db
22,PUBLISHED,The Paper,Oscar-winning composer Tan Dun Inspired by Dun...,谭盾《敦煌·慈悲颂》“回家”,None,None,NaN,Article,2021-03-01T09:03:26.157Z,9d8cd6a2-cf0b-4760-bfb6-8836121ea9d5
23,PUBLISHED,Huxiu,The unconventional idols from this hit reality...,当女权主义遇上年龄焦虑,None,None,NaN,Article,2021-03-01T09:03:26.193Z,533374b1-b384-43b4-a18c-e269e49d638f
24,PUBLISHED,Huxiu / MissXY / The Paper,Foreign investors overwhelmed by domestic dema...,浦东三十年（3）- 被远远低估的市场,None,None,NaN,Article,2021-03-01T09:03:26.106Z,4ac30332-94c8-47a2-844e-d7661165f177
25,PUBLISHED,Global Times,The Chinese legend that shaped the East Asian ...,日本对三国历史文化的狂热,None,None,NaN,Article,2021-03-01T09:03:26.193Z,f26d0abb-876f-4bc9-acba-42ea435c5e3e
26,PUBLISHED,Sohu,Forget your stereotypes of old-fashioned Chine...,新式中餐令人耳目一新,None,None,NaN,Article,2021-03-01T09:03:26.196Z,26468473-7855-44a3-9e6a-a48fb5ce6518
27,PUBLISHED,China Venture,From a Gen-Z niche to investors’ craze,汉服国潮和国风的文化与投资,None,None,NaN,Article,2021-06-21T02:17:21.177Z,f1bf983a-92d7-45f9-904f-b14830b5feb1
28,ARCHIVED,test,test,test,None,None,NaN,Article,2021-07-18T23:43:03.584Z,44162741-7086-4f98-8470-0872599117ce
29,PUBLISHED,Meho Exclusive,Are we drawing conclusions too soon?,新疆的棉花风波,None,None,NaN,Article,2021-03-26T07:33:32.159Z,d0e1c5cc-8f0a-4882-abad-d82df8467449
30,PUBLISHED,Southern Metropolis Daily,Selling a $6-mllion rocket within 5 mins,直播是电商的未来形态,None,None,NaN,Article,2021-03-01T09:03:26.193Z,17d349ef-96d7-4dc8-9949-efdf0b360409
31,PUBLISHED,The New Weekly,How traditional Beijing Opera became the highl...,2亿5千万人在哔哩哔哩跨年,None,None,NaN,Article,2021-03-01T09:03:26.132Z,76f65f04-7df2-4b44-8bff-e716a9130254
32,PUBLISHED,Southern Metropolis Daily,The 600-year Palace has gone viral on social m...,为什么年轻人重新爱上故宫,None,None,NaN,Article,2021-03-01T09:03:26.215Z,e075c5dd-7ee8-4e6b-8d89-dfd719c332fd
33,PUBLISHED,World of Boss,How Shenzhen grew from a village to a city big...,深圳改革开放四十年,None,None,NaN,Article,2021-03-01T09:03:26.158Z,5ba72a1a-5b21-4a29-9c4d-9e2f16b0e451

In [41]:
recentpublishfilter = dfcontent['created_date']>='2021-03-01T09:03:26.193Z' # can be >, >=, ==, <=, <, !=

In [44]:
dfcontent.loc[articlefilter & recentpublishfilter, :]

,status,sourcer,title_english,title_localized,proficiency,parent_id,tag,content_type,created_date,content_id
2,PUBLISHED,The paper,"A Poetic White Domain in Lujiazui, Shanghai",上海陆家嘴浦东美术馆,None,None,NaN,Article,2021-07-19T06:10:31.959Z,bac40260-3415-4231-b54d-fba6845b4bbf
3,PUBLISHED,Yuanchuan Research,Ultra-High Voltage to lower the cost of solar ...,中国碳中和之路-特高压战略,None,None,NaN,Article,2021-05-16T23:46:23.405Z,e4163bea-a1b6-4d97-b604-692f93c84704
4,PUBLISHED,The Paper,China is changing its storytelling style in en...,叛逆神话人物成为全民英雄,None,None,NaN,Article,2021-03-01T09:03:26.215Z,aded84f9-153c-43b3-a0e9-f5680fbeec4a
5,PUBLISHED,36Kr,Social media empowers Chinese fast fashion brands,中国崛起快时尚品牌,None,None,NaN,Article,2021-06-27T23:42:16.990Z,63041c65-b4fb-4aa7-a49a-dfa1cb436c58
7,PUBLISHED,Yuanchuan Research,How scalability made solar power 60% cheaper t...,中国碳中和之路-光伏产业战略,None,None,NaN,Article,2021-05-10T00:55:46.574Z,ec39ec91-b835-4f66-bb63-f0da8ec74aa8
8,PUBLISHED,Sanlian Lifeweek,Father of Hybrid Rice Yuan Longping’s legacy,播下改变中国的种子,None,None,NaN,Article,2021-05-24T00:10:11.675Z,6f9a26fd-3ca0-4732-9496-3de4cc39dbd5
9,ARCHIVED,test,test,test,None,None,NaN,Article,2021-07-18T23:43:13.229Z,7e2e0fac-4839-4650-9e8d-074212cd6142
11,PUBLISHED,Gingko Finance,With unsuitable magic from Harry Potter and Fr...,木兰无法突围,None,None,NaN,Article,2021-03-01T09:03:26.193Z,f06ade97-62d9-4219-8d47-fb2e4ff3cc24
12,PUBLISHED,iFeng Weekly,Tourism in China recovered from COVID-19,史上最挤五一小长假,None,None,NaN,Article,2021-05-03T02:36:59.111Z,392ffe1b-3680-41f7-95eb-269d69905e2d
13,PUBLISHED,Lianhe Zaobao,Why Chinese tech companies work 70+ hours a week?,饱受争议的996工作制,None,None,NaN,Article,2021-03-01T09:03:26.193Z,814426c4-6742-42fc-ac96-317ae971ebe2
15,PUBLISHED,Toutiao,The must-know knowledge in essential Chinese c...,如何在品茶仪式中不犯错误,None,None,NaN,Article,2021-03-01T09:03:26.193Z,5fef42eb-961c-40ec-a917-ee1b9ab26427
16,PUBLISHED,China Business Network,Chinese cities are taking bullet trains to the...,高铁究竟还能跑多快,None,None,NaN,Article,2021-03-01T09:03:26.236Z,5276ce75-6328-4e01-b195-b122253f9ad8
17,PUBLISHED,Yuanchuan Research,Electric vehicle to make solar power storable ...,中国碳中和之路-电动车战略,None,None,NaN,Article,2021-05-31T23:34:30.904Z,5107cb77-aaae-43a7-abe1-743bab145507
18,PUBLISHED,The Paper / Colin Wu,Its impact on carbon neutrality & climate change,中国比特币挖矿的能耗争议,None,None,NaN,Article,2021-04-09T18:52:09.929Z,e6851afa-6134-48e9-a262-278b31f510c0
19,PUBLISHED,Toutiao,The hottest Chinese idol and his phenomenal song,吴亦凡与现象级的《大碗宽面》,None,None,NaN,Article,2021-03-01T09:03:26.194Z,d6203af0-a36b-4ead-84e4-5d7cd564abe4
21,PUBLISHED,Xinmin Evening News,"A day of peace and health, but also happiness",端午安康，端午快乐,None,None,NaN,Article,2021-06-14T02:26:41.839Z,979653e9-962e-44d1-871d-2b31cbb813db
23,PUBLISHED,Huxiu,The unconventional idols from this hit reality...,当女权主义遇上年龄焦虑,None,None,NaN,Article,2021-03-01T09:03:26.193Z,533374b1-b384-43b4-a18c-e269e49d638f
25,PUBLISHED,Global Times,The Chinese legend that shaped the East Asian ...,日本对三国历史文化的狂热,None,None,NaN,Article,2021-03-01T09:03:26.193Z,f26d0abb-876f-4bc9-acba-42ea435c5e3e
26,PUBLISHED,Sohu,Forget your stereotypes of old-fashioned Chine...,新式中餐令人耳目一新,None,None,NaN,Article,2021-03-01T09:03:26.196Z,26468473-7855-44a3-9e6a-a48fb5ce6518
27,PUBLISHED,China Venture,From a Gen-Z niche to investors’ craze,汉服国潮和国风的文化与投资,None,None,NaN,Article,2021-06-21T02:17:21.177Z,f1bf983a-92d7-45f9-904f-b14830b5feb1
28,ARCHIVED,test,test,test,None,None,NaN,Article,2021-07-18T23:43:03.584Z,44162741-7086-4f98-8470-0872599117ce
29,PUBLISHED,Meho Exclusive,Are we drawing conclusions too soon?,新疆的棉花风波,None,None,NaN,Article,2021-03-26T07:33:32.159Z,d0e1c5cc-8f0a-4882-abad-d82df8467449
30,PUBLISHED,Southern Metropolis Daily,Selling a $6-mllion rocket within 5 mins,直播是电商的未来形态,None,None,NaN,Article,2021-03-01T09:03:26.193Z,17d349ef-96d7-4dc8-9949-efdf0b360409
32,PUBLISHED,Southern Metropolis Daily,The 600-year Palace has gone viral on social m...,为什么年轻人重新爱上故宫,None,None,NaN,Article,2021-03-01T09:03:26.215Z,e075c5dd-7ee8-4e6b-8d89-dfd719c332fd

## rename or delete certain column

In [47]:
dfcontent_renamed = dfcontent.rename(columns={'title_english':'title', 'title_localized':'title_zh'})

In [48]:
dfcontent_renamed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6490 entries, 0 to 6489
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   status        86 non-null     object
 1   sourcer       34 non-null     object
 2   title         5810 non-null   object
 3   title_zh      5982 non-null   object
 4   proficiency   45 non-null     object
 5   parent_id     1188 non-null   object
 6   tag           0 non-null      float64
 7   content_type  6490 non-null   object
 8   created_date  6490 non-null   object
 9   content_id    6490 non-null   object
dtypes: float64(1), object(9)
memory usage: 507.2+ KB

In [49]:
dfcontent_dropped = dfcontent.drop(columns=['tag','sourcer'])

In [50]:
dfcontent_dropped.head()

,status,title_english,title_localized,proficiency,parent_id,content_type,created_date,content_id
0,PUBLISHED,From Alibaba’s payment tool to the largest IPO...,支付宝的成长史,None,None,Article,2021-03-01T09:03:26.181Z,a5eb9474-cb94-419c-9ab0-b9ede59422ca
1,PUBLISHED,"30 Years of Development in Pudong, Shanghai - ...",浦东三十年（1）- 邓小平和朱镕基的大动作,None,None,Article,2021-03-01T09:03:26.159Z,a833f110-bc1d-4acc-b832-5bdefff625ee
2,PUBLISHED,"A Poetic White Domain in Lujiazui, Shanghai",上海陆家嘴浦东美术馆,None,None,Article,2021-07-19T06:10:31.959Z,bac40260-3415-4231-b54d-fba6845b4bbf
3,PUBLISHED,Ultra-High Voltage to lower the cost of solar ...,中国碳中和之路-特高压战略,None,None,Article,2021-05-16T23:46:23.405Z,e4163bea-a1b6-4d97-b604-692f93c84704
4,PUBLISHED,China is changing its storytelling style in en...,叛逆神话人物成为全民英雄,None,None,Article,2021-03-01T09:03:26.215Z,aded84f9-153c-43b3-a0e9-f5680fbeec4a

In [51]:
del dfcontent_dropped['proficiency']

In [52]:
dfcontent_dropped.head()

,status,title_english,title_localized,parent_id,content_type,created_date,content_id
0,PUBLISHED,From Alibaba’s payment tool to the largest IPO...,支付宝的成长史,None,Article,2021-03-01T09:03:26.181Z,a5eb9474-cb94-419c-9ab0-b9ede59422ca
1,PUBLISHED,"30 Years of Development in Pudong, Shanghai - ...",浦东三十年（1）- 邓小平和朱镕基的大动作,None,Article,2021-03-01T09:03:26.159Z,a833f110-bc1d-4acc-b832-5bdefff625ee
2,PUBLISHED,"A Poetic White Domain in Lujiazui, Shanghai",上海陆家嘴浦东美术馆,None,Article,2021-07-19T06:10:31.959Z,bac40260-3415-4231-b54d-fba6845b4bbf
3,PUBLISHED,Ultra-High Voltage to lower the cost of solar ...,中国碳中和之路-特高压战略,None,Article,2021-05-16T23:46:23.405Z,e4163bea-a1b6-4d97-b604-692f93c84704
4,PUBLISHED,China is changing its storytelling style in en...,叛逆神话人物成为全民英雄,None,Article,2021-03-01T09:03:26.215Z,aded84f9-153c-43b3-a0e9-f5680fbeec4a

# Aggregation

In [54]:
# dfcontent['fieldname'].sum()  # summing up this column's value, ignoring Null/NaN
# dfcontent.sum() # summing up every column's value, make a table

In [62]:
missing_english_title_filter = dfcontent['title_english'].isna() # create a filter for given column null value

In [60]:
df_content_missing_english_title = dfcontent.loc[missing_english_title_filter, :]

In [61]:
df_content_missing_english_title.head()

,status,sourcer,title_english,title_localized,proficiency,parent_id,tag,content_type,created_date,content_id
5304,None,None,None,电子商务：这是支付宝从一开始就拥有的优势，因为它与淘宝网息息相关。现在，天猫，天猫超市和淘宝...,None,a5eb9474-cb94-419c-9ab0-b9ede59422ca,NaN,Paragraph,2020-09-25T03:46:00.157Z,4a5f952a-7fd3-41dc-b9b9-5c8312bd054c
5306,None,None,None,中国的高质量发展其实包括工作效率的提升，以及更加人性的劳动时间安排。,None,814426c4-6742-42fc-ac96-317ae971ebe2,NaN,Paragraph,2020-08-02T21:44:08.519Z,e550de0c-79c1-4612-957a-31dae8a14bdc
5314,None,None,None,重现古杭州的美景：亭台、小桥、流水、轻舟……处处皆景。店内更有手工艺人、民俗杂家穿行，抚琴，...,None,26468473-7855-44a3-9e6a-a48fb5ce6518,NaN,Paragraph,2020-08-02T22:28:11.837Z,42e6d1c6-280f-4074-80b1-d6250d73064d
5321,None,None,None,为了增强竞争优势，淘宝网试图解决当时中国电子商务中最大的痛点-买卖双方之间的信任。当时，淘宝...,None,a5eb9474-cb94-419c-9ab0-b9ede59422ca,NaN,Paragraph,2020-09-25T03:43:25.079Z,c1d1cbb1-ade3-4a2e-bc8b-86ad8c4ac1c3
5329,None,None,None,以北京至上海为例，加上旅途准备时间，乘飞机需要约四个半小时，高铁需要约五个半小时，而高速磁浮...,None,5276ce75-6328-4e01-b195-b122253f9ad8,NaN,Paragraph,2020-08-02T22:54:55.139Z,535af8c8-d298-4bf3-950b-ee40687d2e08

In [64]:
dfcontent.loc[-missing_english_title_filter, :].head() # NAGATE the filter

,status,sourcer,title_english,title_localized,proficiency,parent_id,tag,content_type,created_date,content_id
0,PUBLISHED,Meho Exclusive,From Alibaba’s payment tool to the largest IPO...,支付宝的成长史,None,None,NaN,Article,2021-03-01T09:03:26.181Z,a5eb9474-cb94-419c-9ab0-b9ede59422ca
1,PUBLISHED,Huxiu / MissXY / The Paper,"30 Years of Development in Pudong, Shanghai - ...",浦东三十年（1）- 邓小平和朱镕基的大动作,None,None,NaN,Article,2021-03-01T09:03:26.159Z,a833f110-bc1d-4acc-b832-5bdefff625ee
2,PUBLISHED,The paper,"A Poetic White Domain in Lujiazui, Shanghai",上海陆家嘴浦东美术馆,None,None,NaN,Article,2021-07-19T06:10:31.959Z,bac40260-3415-4231-b54d-fba6845b4bbf
3,PUBLISHED,Yuanchuan Research,Ultra-High Voltage to lower the cost of solar ...,中国碳中和之路-特高压战略,None,None,NaN,Article,2021-05-16T23:46:23.405Z,e4163bea-a1b6-4d97-b604-692f93c84704
4,PUBLISHED,The Paper,China is changing its storytelling style in en...,叛逆神话人物成为全民英雄,None,None,NaN,Article,2021-03-01T09:03:26.215Z,aded84f9-153c-43b3-a0e9-f5680fbeec4a

In [67]:
dfcontent['title_english'].isna().sum() # True=1/False=0 in python, this way it turn each row into True/False => 1/0, then sum up; typical use to check null value count for a column in DF

680

In [72]:
dropped = dfcontent['title_english'][5000:6000].dropna(how='any')

In [74]:
dropped

5000                                           HSK_LEVEL4
5001                                           HSK_LEVEL5
5002                                           HSK_LEVEL4
5003                                           HSK_LEVEL6
5004                                           HSK_LEVEL6
                              ...
5994    Although the quality and beauty are high level...
5995    I wonder if the top global brands like Burberr...
5997    May Day Holiday in 2021 can be called "the mos...
5998    In April 2019, Shan Jixiang formally stepped d...
5999    Hollywood has never understood China, so it do...
Name: title_english, Length: 702, dtype: object

In [81]:
dfcontent['title_english'][5300:5333].fillna("meaningless")
# dfcontent['title_english'][5300:5333].fillna(method='bfill') -> fill it with the value from next row; 
# or "ffill" -> from previous value
# or "linear" -> avg of previous and next value

5300                                           HSK_LEVEL5
5301                                           HSK_LEVEL6
5302    In the evening after the show went live, someo...
5303    The popularity of EV will re-accelerate the de...
5304                                          meaningless
5305    In Singapore, Zhu Rongji broke even more explo...
5306                                          meaningless
5307    “We get more than 100 letters a day from peopl...
5308    It was like a dream where we all traverse back...
5309    According to the original plan, a 600-km/h hig...
5310    If it is true, the memory of a great patriotic...
5311    Similarly, when there is a lot of cotton to be...
5312    But capital is smart and honest. From 1990 to ...
5313    “I started to read a lot of things, but the mo...
5314                                          meaningless
5315    On August 20, 2020, Ji Keliang, the former cha...
5316    The cost of the medium-to-low speed maglev rai...
5317    The official release poster for Mulan was ridi...
5318    Besides, the dishes also emphasize on visual p...
5319    For example, the same element of magic would n...
5320    Mulan is special in both China and Disney’s pr...
5321                                          meaningless
5322    Hiking on Lunar March 3 and climbing on Lunar ...
5323    The circular system of PV, UHV, and EV has all...
5324    While watching Sisters Who Make Waves, you see...
5325    There are errors in some data in the paper. Fo...
5326    Fast forward to Singles Day of 2019, Xueli pla...
5327    For example, the frequently cited report from ...
5328    At present, China is the country with the high...
5329                                          meaningless
5330    Under the trend of "carbon neutrality", the en...
5331    According to CBN’s 2020 report of alcohol cons...
5332                                          meaningless
Name: title_english, dtype: object

Series([], Name: title_english, dtype: object)

In [82]:
dfcontent.loc[missing_english_title_filter, :].head()

,status,sourcer,title_english,title_localized,proficiency,parent_id,tag,content_type,created_date,content_id
5304,None,None,None,电子商务：这是支付宝从一开始就拥有的优势，因为它与淘宝网息息相关。现在，天猫，天猫超市和淘宝...,None,a5eb9474-cb94-419c-9ab0-b9ede59422ca,NaN,Paragraph,2020-09-25T03:46:00.157Z,4a5f952a-7fd3-41dc-b9b9-5c8312bd054c
5306,None,None,None,中国的高质量发展其实包括工作效率的提升，以及更加人性的劳动时间安排。,None,814426c4-6742-42fc-ac96-317ae971ebe2,NaN,Paragraph,2020-08-02T21:44:08.519Z,e550de0c-79c1-4612-957a-31dae8a14bdc
5314,None,None,None,重现古杭州的美景：亭台、小桥、流水、轻舟……处处皆景。店内更有手工艺人、民俗杂家穿行，抚琴，...,None,26468473-7855-44a3-9e6a-a48fb5ce6518,NaN,Paragraph,2020-08-02T22:28:11.837Z,42e6d1c6-280f-4074-80b1-d6250d73064d
5321,None,None,None,为了增强竞争优势，淘宝网试图解决当时中国电子商务中最大的痛点-买卖双方之间的信任。当时，淘宝...,None,a5eb9474-cb94-419c-9ab0-b9ede59422ca,NaN,Paragraph,2020-09-25T03:43:25.079Z,c1d1cbb1-ade3-4a2e-bc8b-86ad8c4ac1c3
5329,None,None,None,以北京至上海为例，加上旅途准备时间，乘飞机需要约四个半小时，高铁需要约五个半小时，而高速磁浮...,None,5276ce75-6328-4e01-b195-b122253f9ad8,NaN,Paragraph,2020-08-02T22:54:55.139Z,535af8c8-d298-4bf3-950b-ee40687d2e08